name: finzomanager
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.9
  intl: ^0.20.2
  pretty_dio_logger: ^1.4.0
  logger: ^2.7.0
  equatable: ^2.1.0
  either:
    path: ./packages/either
  field_validator:
    path: ./packages/field_validator
  language:
    path: ./packages/language
  themes:
    path: ./packages/themes
  screen_util:
    path: ./packages/screen_util
  dio: ^5.11.0
  go_router: ^17.3.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^10.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.3.0
  get_it: ^9.2.1
  phone_form_field: ^10.0.18
  phone_numbers_parser: ^9.0.24
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.2
  image_picker: ^1.2.3
  url_launcher: ^6.3.2
  flutter_animate: ^4.5.2
  firebase_core: ^4.12.1
  firebase_crashlytics: ^5.2.6
  firebase_analytics: ^12.4.5
  firebase_remote_config: ^6.5.5
  firebase_messaging: ^16.4.3
  flutter_local_notifications: ^22.2.0
  permission_handler: ^12.0.3
  badges: ^3.2.0
  webview_flutter: ^4.14.1
  lottie: ^3.5.1
  path_provider: ^2.1.6
  video_player: ^2.13.0
  chewie: ^1.14.1
  file_picker: ^12.2.0
  device_info_plus: ^13.2.0
  package_info_plus: ^10.2.1
  store_redirect: ^2.0.4
  flutter_html: ^3.0.0
  share_plus: ^13.3.0
  font_awesome_flutter: ^11.0.0
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^8.2.0
  drift: ^2.35.1
  drift_flutter: ^0.3.1
  sqlite3_flutter_libs: ^0.6.0+eol
  path: ^1.9.1
  firebase_auth: ^6.7.0
  firebase_storage: ^13.6.0
  internet_connection_checker_plus: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  go_router_builder: ^4.4.0
  build_runner: ^2.15.1
  bloc_test: ^10.0.0
  mockito: ^5.6.4
  integration_test:
    sdk: flutter
  drift_dev: ^2.35.1


flutter:
  uses-material-design: true

  assets:
    - language.yaml
    - assets/
    - assets/lang/
    - assets/icons/
    - assets/images/
    - assets/anim/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100

