///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String animClockLoadingDark =
      'assets/anim/clock-loading-dark.json';
  static const String animClockLoadingLight =
      'assets/anim/clock-loading-light.json';
  static const String animSuccess1732061823350 =
      'assets/anim/success-1732061823350.json';
  static const String iconsAddBookmark = 'assets/icons/add-bookmark.svg';
  static const String iconsBookmark = 'assets/icons/bookmark.svg';
  static const String iconsBookmarks = 'assets/icons/bookmarks.svg';
  static const String iconsBuilding = 'assets/icons/building.svg';
  static const String iconsCamera = 'assets/icons/camera.svg';
  static const String iconsChangePassword = 'assets/icons/change_password.svg';
  static const String iconsClosed = 'assets/icons/closed.svg';
  static const String iconsDots = 'assets/icons/dots.svg';
  static const String iconsDownload = 'assets/icons/download.svg';
  static const String emptyWhiteBox = 'assets/icons/empty-white-box.svg';
  static const String iconsFingerprint = 'assets/icons/fingerprint.svg';
  static const String iconsGraduationCap = 'assets/icons/graduation-cap.svg';
  static const String iconsHome = 'assets/icons/home.svg';
  static const String iconsHomeSelected = 'assets/icons/home-selected.svg';
  static const String iconsJobs = 'assets/icons/jobs.svg';
  static const String iconsLogout = 'assets/icons/logout.svg';
  static const String iconsNotification = 'assets/icons/notification.svg';
  static const String iconsNotifications = 'assets/icons/notifications.svg';
  static const String iconsPencil = 'assets/icons/pencil.svg';
  static const String iconsQuote = 'assets/icons/quote.svg';
  static const String iconsSearch = 'assets/icons/search.svg';
  static const String iconsSecureShield = 'assets/icons/secure-shield.svg';
  static const String iconsSettings = 'assets/icons/settings.svg';
  static const String iconsSuccess = 'assets/icons/success.svg';
  static const String iconsTrashX = 'assets/icons/trash-x.svg';
  static const String iconsTrophy = 'assets/icons/trophy.svg';
  static const String iconsUpload = 'assets/icons/upload.svg';
  static const String iconsUser = 'assets/icons/user.svg';
  static const String iconsUserDelete = 'assets/icons/user-delete.svg';
  static const String iconsUserEdit = 'assets/icons/user-edit.svg';
  static const String iconsUserPlus = 'assets/icons/user-plus.svg';
  static const String iconsUsers = 'assets/icons/users.svg';
  static const String iconsVerify = 'assets/icons/verify.svg';
  static const String imagesLogoBlack = 'assets/images/logo-black.png';
  static const String imagesLogoSBlack = 'assets/images/logo-s-black.png';
  static const String imagesLogoSWhite = 'assets/images/logo-s-white.png';
  static const String imagesLogoSWhiteShadow =
      'assets/images/logo-s-white-shadow.png';
  static const String imagesLogoWhite = 'assets/images/logo-white.png';
  static const String imagesPlaceholder = 'assets/images/placeholder.jpg';
  static const String imagesPlaceholderCompany =
      'assets/images/placeholder-company.png';
  static const String imagesPlaceholderUser =
      'assets/images/placeholder-user.png';
  static const String langAr = 'assets/lang/ar.json';
  static const String langEn = 'assets/lang/en.json';
  static const String poppinsPoppinsBlack =
      'assets/fonts/Poppins/Poppins-Black.ttf';
  static const String poppinsPoppinsBold =
      'assets/fonts/Poppins/Poppins-Bold.ttf';
  static const String poppinsPoppinsExtraBold =
      'assets/fonts/Poppins/Poppins-ExtraBold.ttf';
  static const String poppinsPoppinsExtraLight =
      'assets/fonts/Poppins/Poppins-ExtraLight.ttf';
  static const String poppinsPoppinsLight =
      'assets/fonts/Poppins/Poppins-Light.ttf';
  static const String poppinsPoppinsMedium =
      'assets/fonts/Poppins/Poppins-Medium.ttf';
  static const String poppinsPoppinsRegular =
      'assets/fonts/Poppins/Poppins-Regular.ttf';
  static const String poppinsPoppinsSemiBold =
      'assets/fonts/Poppins/Poppins-SemiBold.ttf';
  static const String poppinsPoppinsThin =
      'assets/fonts/Poppins/Poppins-Thin.ttf';
}
