name: field_validator
description: A flexible, configurable input and form field validation package with formatters and customizable message defaults.
version: 1.0.0

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/lang/
